config/routes.rb
Flix::Application.routes.draw do

  
  root 'welcome#index'
  resources :movies

  end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
def index
	@movies = Movie.all
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
def index
	
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def format_total_gross(m)

    if m.total_gross > 300
      content_tag(:strong, 'Yop')

    else
      content_tag(:strong, 'Flop')
    end

  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flix</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/index.html.erb
<h1>Movies</h1>
<h2> <%= pluralize(@movies.size, 'movie') %>.</h2>
<ul>
  <% @movies.each do |m| %>

      <li><strong><%= link_to m.id, @movie %>
       <%= link_to m.id, controller: 'movies', action: 'show', id: m.id %>
        - <%= link_to m.title, controller: 'movies', action: 'show', id: m.id%></strong>
        - Mis à jour : <%= m.updated_at %>
        <br>
        Description : <br>
        <%= truncate(m.description, length: 140, separator: ' ') %> <br>


        Chiffre d'affaire :   <%= format_total_gross(movie)%>


        Date de sortie le : <%= m.released_on %>





      </li>
  <% end %>
</ul>

<%= link_to "Accueil", root_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Flix !! </h1>
<h2> It's good to be the King...</h2>

<%= link_to "Liste des films", movies_path %>